### PR TITLE
Add support for multiple Canadian retailers

### PR DESCRIPTION
**Pull request by MRizkBV**
Add support for CanadaComputers, EBGames, ToysRUs, Costco Canada.

@EricJMarti 
I wanted to add support for the following retailers but faced some issues:
- Amazon.ca: I get a float error as the currency field has text (CDN$ 99.99 for example)
- MemoryExpress: I get a float error as MemoryExpress has the word "Only" before the number
- Walmart.ca: Gets detected as a bot instantly, even when using selenium

### CODE REVIEW

**Comment by EricJMarti** [comment]
Do you know if the Costco scraper works on the US site?

I haven't found a good way of handling prices yet, so I may change the code to simply look for a number in the price string and ignore any currency symbols. Fortunately, I don't think the price conversion bug actually prevents alerts from going out.

Also, can you take a look at the unit test suite I put together for scrapers? Basically, when you run a scraper, it dumps the html to `inventory-hunter/data/${container_name}`. From there, you can copy the contents into the tests directory and spin up a unit test for the parsing logic. You can use the `run_tests.bash` script to run the test suite.

**Comment by MRizkBV** [comment]
> Do you know if the Costco scraper works on the US site?
> 
> I haven't found a good way of handling prices yet, so I may change the code to simply look for a number in the price string and ignore any currency symbols. Fortunately, I don't think the price conversion bug actually prevents alerts from going out.
> 
> Also, can you take a look at the unit test suite I put together for scrapers? Basically, when you run a scraper, it dumps the html to `inventory-hunter/data/${container_name}`. From there, you can copy the contents into the tests directory and spin up a unit test for the parsing logic. You can use the `run_tests.bash` script to run the test suite.

1. I did not try with Costco.com as the PS5 they sell is a member only item and I guess that means there is no way to know when it is in stock
2. That's correct, the script can ignore the price but that mean it will send alerts for items sold by scalpers incase of Amazon.ca for example. The alternative option is to ignore add to cart and look for sold and shipped by Amazon.ca instead. That is something I plan to do for my personal use.
3. I will take a look at the test suite. Thanks 👍🏻

**Comment by EricJMarti** [comment]
Also, interesting find regarding walmart.ca. It seems the US site doesn't have the same level of protection; I get a reCAPTCHA when I try scraping the Canadian site.

**Comment by MRizkBV** [comment]
> Also, interesting find regarding walmart.ca. It seems the US site doesn't have the same level of protection; I get a reCAPTCHA when I try scraping the Canadian site.

They are taking it so serious. Not just reCAPTCHA. They also show all products as unavailable if you connect using a known VPN provider/data center range.

**Comment by EricJMarti** [comment]
Can you try Amazon.ca again with the latest image? I recently committed a change that was intended to ignore currency symbols.

**Comment by MRizkBV** [comment]
> Can you try Amazon.ca again with the latest image? I recently committed a change that was intended to ignore currency symbols.

@EricJMarti It works now with Amazon.ca, MemoryExpress and eBuyer (UK).

I have tried adding so many other sites over the week and had success with most but a few:

Amazon.de/.nl do not seem to work. Error: "unable to find price in string: "€ 624,02" 

AntOnline/ZotacStore have false positives and no matter what I change they always send false positives.

**Comment by EricJMarti** [comment]
I just checked in a change that should fix amazon.de and similar sites: https://github.com/EricJMarti/inventory-hunter/commit/171f261a39f5c463caff921efcd8f9d36f5bc681

Can you try these sites again? I'm really hoping this commit fixes a majority of the international price conversion issues we're seeing.

**Comment by EricJMarti** [comment]
@MRizkBV Thanks for your contribution!

Also, I just put together this wiki page: https://github.com/EricJMarti/inventory-hunter/wiki/Retailer-Support-Matrix

I'll add these retailers to the matrix.

**Pull request merged**
