### PR TITLE
Move Discord mentions to main message, and show role name instead of ID

### PR DESCRIPTION
**Pull request by MRizkBV**
I thought it would look better moving the Discord mention to the main message instead embed, and show the role name instead of the ID.

### CODE REVIEW

**Comment by MRizkBV** [comment]
Sorry for the so many changes. I just didn't know that any following modifications I do on my fork would reflect back here on the pull request. This is literally my first pull request on GitHub.

**Comment by EricJMarti** [comment]
Instead of hard-coding the ampersand in discord.py, could you add it into your alerter config? This change may break some users currently using the mentions feature with user IDs. For instance, I get alerts tagged `@deleted-role` after this change.

**Comment by MRizkBV** [comment]
I believe this should fix it. (Hopefully).

**Comment by EricJMarti** [comment]
Thank you!

**Pull request merged**
