### PR TITLE
add Sams Club scraper plus Sam's SKUs config file

### PR DESCRIPTION
**Pull request by frantisekbrabec**
note that pages for prod25090927 and prod25090932 seem to load in two steps, first it shows page content as if the product was available which is immediately updated by another content which shows the product to be sold out. As a result, the driver reports false positives for these two items, probably needs to be updated so that it waits for the page to load the updates before acting upon its content.

### CODE REVIEW

**Comment by MRizkBV** [comment]
It seems to be giving me false positives for the following links;
https://www.samsclub.com/p/pny-geforce-rtx3070-8gb-graphics-card/prod25090927
https://www.samsclub.com/p/pny-geforce-rtx3090-24gb-graphics-card/prod25090932

They are both out of stock but the bot seems to believe they are in stock.

**Comment by frantisekbrabec** [comment]
Yeah, I know, as per the preceding comment. You can see for yourself in a regular browser that the page actually shows availability briefly and that's what the scraper reports. Hopefully, someone will be able to improve upon this, until then I guess you won't be able to track those two items.

**Comment by EricJMarti** [comment]
Have you tried changing the selenium driver's page load strategy from "eager" to "normal" in driver.py: https://github.com/EricJMarti/inventory-hunter/blob/a3efe6ac4203e09e51360a6bc9438e4405e1cddf/src/driver.py#L45

Also see: https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/

**Comment by frantisekbrabec** [comment]
> Have you tried changing the selenium driver's page load strategy from "eager" to "normal" in driver.py:
> 
> https://github.com/EricJMarti/inventory-hunter/blob/a3efe6ac4203e09e51360a6bc9438e4405e1cddf/src/driver.py#L45
> 
> Also see: https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/

I did. I also tried 

`driver.implicitly_wait(10) # seconds`

Neither works. Was hoping someone who knows what they are doing could resolve quickly.

**Pull request merged**
