### PR TITLE
WIP: Making Alerter class more modular (Discord Intergration +  others) 

### PR DESCRIPTION
**Pull request by ms7m**
Tried to make it more modular. Found it to work nicely with discord/slack. 
I tried to make it as compatible with existing code as possible.

Extremely open to feedback.

### CODE REVIEW

**Comment by ms7m** [comment]
Example CLI Usage 

```
python.py run -a discord -w "https://webhook.url" --config=...
python.py run -a slack -w "https://webhook.url" --config=...
python.py run -a email -r="Relay IP Address -e="Email Recipient" --config=...
```

**Comment by alexgraham** [comment]
Just tried to test but running into a local issue. I `git pull origin pull/34/head` and `docker build -t inventory-hunter .` no errors.

I then try and run it using `./docker_run.bash -a discord -w "https://discord.com/api/webhooks/..." -c "config/rtx_3080.yaml"` and get the error:
`./docker_run.bash: illegal option -- a
error: missing config argument
usage: ./docker_run.bash -c CONFIG -e EMAIL -r RELAY`

I'm seeing your updated code though so -a or --alerter= should be valid. First time I've used Docker and Python so I must be doing something wrong here.

**Comment by EricJMarti** [comment]
This is really awesome! I'll pull in your branch later today and give it a try.

**Comment by ms7m** [comment]
@alexgraham 

Yeah, Looks like docker isn't really working. Didn't touch much on that one. But it worked great for me when replicating the environment in a normal python way.

Not too familiar with docker so hopefully someone can assist in this.

**Comment by alexgraham** [comment]
Issue was with docker_run.bash, hacked at it so it accepts the new arguments for -a -w

This works wonderfully, near instant alert with Discord. Thanks @ms7m

**Comment by EricJMarti** [comment]
@ms7m Thanks for your work on this!

Just a heads up that I committed a small fix to a typo in the `EmailAlerter` (`self.relat` -> `self.relay`).

**Pull request merged**
